#!/usr/bin/env bash
# DrValue MQTT — 비밀번호 + MySQL 초기화 스크립트 + .env 생성기
# 최초 1회 실행 후, docker compose up 하면 학생 DB까지 자동 구성됩니다.
set -euo pipefail

cd "$(dirname "$0")"

ENV_FILE=".env"
INIT_SQL="docker/mysql/init/01-init.sql"
CREDS_FILE="credentials.txt"

if [ -f "$ENV_FILE" ] || [ -f "$INIT_SQL" ]; then
  echo "이미 .env 또는 docker/mysql/init/01-init.sql 이 존재합니다."
  echo "재생성하려면 다음을 실행 후 다시:"
  echo "  docker compose down -v   # MySQL 볼륨 제거 (데이터 소실)"
  echo "  rm -f $ENV_FILE $INIT_SQL $CREDS_FILE"
  exit 1
fi

genpass() {
  LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32
  echo
}

ROOT_PASS=$(genpass)
PUB_PASS=$(genpass)
ADMIN_USER="admin"
ADMIN_PASS=$(genpass)
T1_PASS=$(genpass)
T2_PASS=$(genpass)
T3_PASS=$(genpass)
T4_PASS=$(genpass)
T5_PASS=$(genpass)

# .env (docker-compose + publisher 모두 공유)
cat > "$ENV_FILE" <<EOF
# Auto-generated by setup.sh — DO NOT COMMIT
MYSQL_ROOT_PASSWORD=$ROOT_PASS

# Publisher → MySQL (host에서 pm2로 띄우면 localhost:3306, 컨테이너에서 띄우면 mysql:3306)
DB_HOST=127.0.0.1
DB_PORT=3306
DB_USER=publisher
DB_PASSWORD=$PUB_PASS
DB_DATABASE=drvalue

# Publisher → MQTT
MQTT_BROKER=mqtt://localhost:1883
PORT=3000

# 강사 모니터링 대시보드 (Basic Auth)
ADMIN_USER=$ADMIN_USER
ADMIN_PASSWORD=$ADMIN_PASS
EOF
chmod 600 "$ENV_FILE"

# MySQL init script (컨테이너 첫 부팅 시 실행됨)
cat > "$INIT_SQL" <<EOF
-- Auto-generated by setup.sh — DO NOT COMMIT
-- 이 파일은 MySQL 컨테이너 최초 부팅 시 1회만 실행됩니다.

-- root 외부 접속 차단: docker entrypoint가 만드는 'root'@'%' 제거
DROP USER IF EXISTS 'root'@'%';

-- Publisher 전용 DB + 계정
CREATE DATABASE IF NOT EXISTS drvalue
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'publisher'@'%' IDENTIFIED BY '$PUB_PASS';
GRANT ALL PRIVILEGES ON drvalue.* TO 'publisher'@'%';

-- 학생 팀별 DB + 계정 (자기 DB만 접근 가능)
CREATE DATABASE IF NOT EXISTS team1 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'team1'@'%' IDENTIFIED BY '$T1_PASS';
GRANT ALL PRIVILEGES ON team1.* TO 'team1'@'%';

CREATE DATABASE IF NOT EXISTS team2 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'team2'@'%' IDENTIFIED BY '$T2_PASS';
GRANT ALL PRIVILEGES ON team2.* TO 'team2'@'%';

CREATE DATABASE IF NOT EXISTS team3 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'team3'@'%' IDENTIFIED BY '$T3_PASS';
GRANT ALL PRIVILEGES ON team3.* TO 'team3'@'%';

CREATE DATABASE IF NOT EXISTS team4 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'team4'@'%' IDENTIFIED BY '$T4_PASS';
GRANT ALL PRIVILEGES ON team4.* TO 'team4'@'%';

CREATE DATABASE IF NOT EXISTS team5 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'team5'@'%' IDENTIFIED BY '$T5_PASS';
GRANT ALL PRIVILEGES ON team5.* TO 'team5'@'%';

FLUSH PRIVILEGES;
EOF

# 강사용 자격증명 요약 (gitignored)
cat > "$CREDS_FILE" <<EOF
# DrValue MQTT — Generated Credentials
# Generated: $(date '+%Y-%m-%d %H:%M:%S %Z')
# 절대 외부에 노출 금지. 학생들에게는 본인 팀 항목만 전달.

[MySQL Root]
  - 외부 접속 불가 (보안). 컨테이너 내부에서만 사용.
  - 사용 예: docker exec -it drvalue-mysql mysql -uroot -p
  - password: $ROOT_PASS

[Publisher 계정 (강사 운영용)]
  - host:     127.0.0.1 (서버 localhost) / mysql (컨테이너 내부)
  - port:     3306
  - database: drvalue
  - user:     publisher
  - password: $PUB_PASS

[강사 모니터링 대시보드]
  - URL:      http://<서버 공인 IP>:3000/admin/
  - user:     $ADMIN_USER
  - password: $ADMIN_PASS
  - 비고:     브라우저 기본 Basic Auth 다이얼로그로 로그인됩니다.
              학생들에게는 절대 공유하지 마세요.

[학생 팀 DB — 각 팀에 본인 항목만 전달]

  ## team1
  - host:     <서버 공인 IP>
  - port:     3306
  - database: team1
  - user:     team1
  - password: $T1_PASS
  - JDBC:     jdbc:mysql://<서버IP>:3306/team1?useSSL=false&serverTimezone=Asia/Seoul

  ## team2
  - host:     <서버 공인 IP>
  - port:     3306
  - database: team2
  - user:     team2
  - password: $T2_PASS
  - JDBC:     jdbc:mysql://<서버IP>:3306/team2?useSSL=false&serverTimezone=Asia/Seoul

  ## team3
  - host:     <서버 공인 IP>
  - port:     3306
  - database: team3
  - user:     team3
  - password: $T3_PASS
  - JDBC:     jdbc:mysql://<서버IP>:3306/team3?useSSL=false&serverTimezone=Asia/Seoul

  ## team4
  - host:     <서버 공인 IP>
  - port:     3306
  - database: team4
  - user:     team4
  - password: $T4_PASS
  - JDBC:     jdbc:mysql://<서버IP>:3306/team4?useSSL=false&serverTimezone=Asia/Seoul

  ## team5
  - host:     <서버 공인 IP>
  - port:     3306
  - database: team5
  - user:     team5
  - password: $T5_PASS
  - JDBC:     jdbc:mysql://<서버IP>:3306/team5?useSSL=false&serverTimezone=Asia/Seoul

[MQTT 토픽 매핑]
  team1 → drvalue/tenant-1
  team2 → drvalue/tenant-2
  team3 → drvalue/tenant-3
  team4 → drvalue/tenant-4
  team5 → drvalue/tenant-5
EOF
chmod 600 "$CREDS_FILE"

echo "✓ 생성 완료:"
echo "  - $ENV_FILE        (docker-compose + publisher용 환경변수)"
echo "  - $INIT_SQL        (MySQL 첫 부팅 시 실행될 초기화)"
echo "  - $CREDS_FILE      (강사용 전체 자격증명 요약)"
echo ""
echo "다음 단계:"
echo "  1. docker compose up -d        # MySQL + Mosquitto 기동"
echo "  2. cd publisher && npm install"
echo "  3. pm2 restart drvalue-publisher --update-env  (또는 새로 start)"
echo "  4. cat $CREDS_FILE             # 학생 팀별 정보 확인 후 전달"
